# -*- coding: utf-8 -*-
"""cal_ag_batch_k_means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZggUzg7CWlWpwPsJasG2B4tLaLPyjxg-

# **Monitoreo de la Calidad del Agua Mediante Algoritmos de Aprendizaje Automático**


(Agregar descripción)

### Debemos instalar algunas dependencias para leer el archivo "xlsb" con el comando "!pip install pyxlsb"
(solo si es necesario)
"""

# instalar dependencias

!pip install pyxlsb

"""### Importamos las librerías"""

# librerias

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# modulos

from seaborn import palettes
from sklearn.cluster import MiniBatchKMeans

# import warnings
# warnings.filterwarnings("ignore")

"""### Creamos la conexión con Google

(Solo si es necesario)
"""

if __name__ == "__main__":

    # creamos la conexión con google

    from google.colab import drive
    drive.mount('/content/drive')    # nobre de la conexion

    # o subimos un archivo (si es necesario)

    # from google.colab import files
    # Uploaded = files.upload()

"""### Creamos una variable con el nuevo archivo"""

## leemos los archivos

    ### leemos el archivo y especificamos la hoja que usaremos como df
    ch_dbo_1 = pd.read_excel('/content/drive/MyDrive/UAM/Calidad del agua /ica_sup_1.xlsx', sheet_name = 'CASUP_2012-2021')

    ## eliminamos las columnas innecesarias

## tratamiento de los valores atipicos y nulos

    ### eliminar los valores nulos
    ch_dbo_1_0 = ch_dbo_1.dropna()

    ### cambia los valores atipicos por 0
    ch_dbo_1_0_0 = ch_dbo_1_0.replace({'<30':30, '<3':3, '<2':2, '<10':10})
    ### tamaño de los datos
    print(ch_dbo_1.shape)
    print(ch_dbo_1_0.shape)
    # ### tipos de datos
    print(ch_dbo_1_0_0.dtypes)
    ### descripción del df
    print(ch_dbo_1_0_0.describe())
    ### eliminamos las columnas que no usaremos
    ch_dbo_1_0_1 = ch_dbo_1_0_0.drop('SITIO', axis = 1)
    print(ch_dbo_1_0_1)

"""## Bach K-Means"""

## batch k-means

    ###  eliminamos las
    X = ch_dbo_1_0_1.drop('SEMAFORO', axis = 1)

    kmeans = MiniBatchKMeans(n_clusters = 3,batch_size = 8).fit(X)

    print('Total de centros: ', len(kmeans.cluster_centers_))
    print('*'*64)
    print(kmeans.predict(X))

    ch_dbo_1_0_2['GROUP'] = kmeans.predict(X)

    print(ch_dbo_1_0_2)

"""# Exportamos el archivo con las predicciones"""

ch_dbo_1_0_1.to_csv('ind_ica.csv')

from google.colab import files
files.download('ind_ica.csv')